// pages.js — generated by the admin panel (/admin). Edit slides there, not by hand.
//
// PAGES[0] is slide 1. Page count is auto-derived from PAGES.length in flipbook.js.
// Each entry is { kind:"image", image } or { kind:"video", video }. Videos may add
// { loop:true } and { overlay, overlayAlt }; floor-plan slides add { download:true,
// downloadUrl, mobileImage }.
(function () {
  window.COVER_IMAGE_URL = "https://d1j3fd6wolejlf.cloudfront.net/ceano-book-cover-(1).png";
  window.PAGES = [
  {
    "kind": "video",
    "video": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_1.webm",
    "alt": "Ceano opening motion"
  },
  {
    "kind": "video",
    "video": "https://d1j3fd6wolejlf.cloudfront.net/Ceano-Logo-Animation_Final.mp4",
    "alt": "Ceano logo animation"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/ceano_digital_preview_4.png",
    "alt": "Ceano slide 4"
  },
  {
    "kind": "video",
    "video": "https://d1j3fd6wolejlf.cloudfront.net/Building-Sketch_with-signature.mp4",
    "alt": "Building sketch with signature"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_6_2.webp",
    "alt": "Ceano slide 8"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_7.webp",
    "alt": "Ceano slide 9"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_8.webp",
    "alt": "Ceano facade"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_10.webp",
    "alt": "Ceano slide 11"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_11_1.webp",
    "alt": "Ceano slide 12"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/ceano_digital_preview_12.png",
    "alt": "Ceano slide 13"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_26.webp",
    "alt": "Ceano slide 14"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/ceano_salespresentation_Rooftop-2.png",
    "alt": "Ceano slide 16"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_29.webp",
    "alt": "Ceano slide 17"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_31.webp",
    "alt": "Ceano slide 18"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_33.webp",
    "alt": "Ceano slide 19"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_57.webp",
    "alt": "Ceano slide 6"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/ceano_digital_preview_7.png",
    "alt": "Ceano slide 7"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_37.webp",
    "alt": "Ceano slide 20"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_38.webp",
    "alt": ""
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/ceano_digital_preview20.png",
    "alt": ""
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_40.webp",
    "alt": ""
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/ceano_digital_preview22.png",
    "alt": ""
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_45.webp",
    "alt": ""
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_46.webp",
    "alt": ""
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/ceano_24_residences.png",
    "alt": "Ceano slide 21"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/new_201.png",
    "alt": "Ceano slide 22",
    "download": true,
    "downloadUrl": "https://d1j3fd6wolejlf.cloudfront.net/CEANO_Residence-201.pdf",
    "mobileImage": "https://d1j3fd6wolejlf.cloudfront.net/210-mobile.png"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/new_202.png",
    "alt": "Ceano slide 23",
    "download": true,
    "downloadUrl": "https://d1j3fd6wolejlf.cloudfront.net/CEANO_Residence-202.pdf",
    "mobileImage": "https://d1j3fd6wolejlf.cloudfront.net/202-mobile.png"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/new_302.png",
    "alt": "Ceano slide 24",
    "download": true,
    "downloadUrl": "https://d1j3fd6wolejlf.cloudfront.net/CEANO_Residence-302.pdf",
    "mobileImage": "https://d1j3fd6wolejlf.cloudfront.net/302-mobile.png"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/new_303.png",
    "alt": "Ceano slide 25",
    "download": true,
    "downloadUrl": "https://d1j3fd6wolejlf.cloudfront.net/CEANO_Residence-303.pdf",
    "mobileImage": "https://d1j3fd6wolejlf.cloudfront.net/303-mobile.png"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/new_406.png",
    "alt": "Ceano slide 26",
    "download": true,
    "downloadUrl": "https://d1j3fd6wolejlf.cloudfront.net/CEANO_Residence-406.pdf",
    "mobileImage": "https://d1j3fd6wolejlf.cloudfront.net/406-mobile.png"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/new_Villa-4.png",
    "alt": "Ceano slide 27",
    "download": true,
    "downloadUrl": "https://d1j3fd6wolejlf.cloudfront.net/CEANO_Villa-4.pdf",
    "mobileImage": "https://d1j3fd6wolejlf.cloudfront.net/villa4-mobile.png"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/Lv_CEANO_Slide_59.webp",
    "alt": "Ceano slide 28"
  },
  {
    "kind": "image",
    "image": "https://d1j3fd6wolejlf.cloudfront.net/with-titles.png",
    "alt": "Ceano slide 3"
  },
  {
    "kind": "video",
    "video": "https://d1j3fd6wolejlf.cloudfront.net/Waves-Background.mp4",
    "alt": "Waves background",
    "loop": true,
    "overlay": "Thank%20You.svg",
    "overlayAlt": "Thank you"
  }
];
})();
